apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:latest
        ports:
        - containerPort: 1025  # SMTP port
        - containerPort: 8025  # Web UI port
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"

---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  labels:
    app: mailhog
spec:
  selector:
    app: mailhog
  type: ClusterIP
  ports:
  - name: smtp
    port: 1025
    targetPort: 1025
  - name: web
    port: 8025
    targetPort: 8025

---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-web
  labels:
    app: mailhog
spec:
  selector:
    app: mailhog
  type: NodePort
  ports:
  - name: web
    port: 8025
    targetPort: 8025
    nodePort: 30825
