apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-webhook
  labels:
    app: alert-webhook
data:
  app.py: |
    from flask import Flask, request, jsonify
    import json
    import datetime
    import logging

    app = Flask(__name__)
    logging.basicConfig(level=logging.INFO)

    @app.route('/webhook', methods=['POST'])
    def webhook():
        data = request.json
        timestamp = datetime.datetime.now().isoformat()

        print(f"\n{'='*50}")
        print(f"ALERT RECEIVED at {timestamp}")
        print(f"{'='*50}")

        if 'alerts' in data:
            for alert in data['alerts']:
                status = alert.get('status', 'unknown')
                alertname = alert.get('labels', {}).get('alertname', 'Unknown')
                severity = alert.get('labels', {}).get('severity', 'unknown')
                instance = alert.get('labels', {}).get('instance', 'unknown')

                print(f"Alert: {alertname}")
                print(f"Status: {status}")
                print(f"Severity: {severity}")
                print(f"Instance: {instance}")

                annotations = alert.get('annotations', {})
                if 'summary' in annotations:
                    print(f"Summary: {annotations['summary']}")
                if 'description' in annotations:
                    print(f"Description: {annotations['description']}")
                if 'runbook_url' in annotations:
                    print(f"Runbook: {annotations['runbook_url']}")

                print(f"Raw alert data: {json.dumps(alert, indent=2)}")
                print("-" * 30)

        print(f"Raw webhook data: {json.dumps(data, indent=2)}")
        print(f"{'='*50}\n")

        return jsonify({"status": "received"}), 200

    @app.route('/health', methods=['GET'])
    def health():
        return jsonify({"status": "healthy"}), 200

    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=5001, debug=True)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-webhook
  labels:
    app: alert-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-webhook
  template:
    metadata:
      labels:
        app: alert-webhook
    spec:
      containers:
      - name: alert-webhook
        image: python:3.9-slim
        command: ['sh', '-c']
        args:
          - |
            pip install flask &&
            cd /app &&
            python app.py
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: webhook-code
          mountPath: /app
      volumes:
      - name: webhook-code
        configMap:
          name: alert-webhook

---
apiVersion: v1
kind: Service
metadata:
  name: alert-webhook
  labels:
    app: alert-webhook
spec:
  selector:
    app: alert-webhook
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
