{
 "title": "Microservices Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", image!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Microservices Logs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(service)" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"default\", service=~\"$service\"}"
    }
   ]
  }
 ]
}
{
 "title": "SecOps dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Critical vulnerabilities",
   "type": "bargauge",
   "description": "critical issues by image.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(trivy_critical) by (image)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "High vulnerabilities",
   "type": "bargauge",
   "description": "Trivy results on image scan with high issues.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(trivy_high) by (image)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "top 5 images with most issues",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, trivy_critical) + trivy_high + trivy_medium + trivy_low",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}